#!/bin/bash
#
# LOD-MCP Installation Script
# Sets up the Luxembourgish Online Dictionary MCP server
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_NAME="lod-mcp"

# Print functions
print_header() {
    echo -e "\n${BLUE}=== $1 ===${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${YELLOW}ℹ${NC} $1"
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Detect Python version
detect_python() {
    if command_exists python3; then
        PYTHON_CMD="python3"
        PYTHON_VERSION=$($PYTHON_CMD --version 2>&1 | cut -d' ' -f2)
        print_success "Found Python $PYTHON_VERSION"
        return 0
    elif command_exists python; then
        PYTHON_CMD="python"
        PYTHON_VERSION=$($PYTHON_CMD --version 2>&1 | cut -d' ' -f2)
        print_success "Found Python $PYTHON_VERSION"
        return 0
    else
        return 1
    fi
}

# Check Python version (need 3.10+)
check_python_version() {
    local major=$(echo $PYTHON_VERSION | cut -d. -f1)
    local minor=$(echo $PYTHON_VERSION | cut -d. -f2)
    
    if [ "$major" -ge 3 ] && [ "$minor" -ge 10 ]; then
        print_success "Python version is compatible (≥3.10)"
        return 0
    else
        print_error "Python 3.10+ required (found $PYTHON_VERSION)"
        return 1
    fi
}

# Detect package manager (uv or pip)
detect_package_manager() {
    if command_exists uv; then
        PKG_MANAGER="uv"
        print_success "Found uv (fast Python package manager)"
    elif command_exists pip3; then
        PKG_MANAGER="pip3"
        print_info "Using pip3"
    elif command_exists pip; then
        PKG_MANAGER="pip"
        print_info "Using pip"
    else
        return 1
    fi
}

# Create virtual environment
create_venv() {
    print_header "Creating Virtual Environment"
    
    if [ -d "$SCRIPT_DIR/.venv" ]; then
        print_info "Virtual environment already exists at .venv/"
        read -p "Remove and recreate? (y/N) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -rf "$SCRIPT_DIR/.venv"
            print_info "Removed existing virtual environment"
        else
            print_info "Using existing virtual environment"
            return 0
        fi
    fi
    
    if [ "$PKG_MANAGER" == "uv" ]; then
        uv venv "$SCRIPT_DIR/.venv" --python=3.13 2>/dev/null || uv venv "$SCRIPT_DIR/.venv"
    else
        $PYTHON_CMD -m venv "$SCRIPT_DIR/.venv"
    fi
    
    print_success "Created virtual environment at .venv/"
}

# Install dependencies
install_deps() {
    print_header "Installing Dependencies"
    
    if [ "$PKG_MANAGER" == "uv" ]; then
        uv pip install mcp requests --system
    else
        source "$SCRIPT_DIR/.venv/bin/activate"
        $PKG_MANAGER install mcp requests
    fi
    
    print_success "Installed mcp and requests"
}

# Create wrapper script
create_wrapper() {
    print_header "Creating Wrapper Script"
    
    local venv_python="$SCRIPT_DIR/.venv/bin/python"
    local venv_site_packages="$SCRIPT_DIR/.venv/lib/python*/site-packages"
    
    # Find the exact site-packages path
    local site_packages_path=$(find "$SCRIPT_DIR/.venv/lib" -name "site-packages" -type d | head -1)
    
    cat > "$SCRIPT_DIR/run-mcp.sh" << EOF
#!/bin/bash
# LOD-MCP Wrapper Script
# Auto-generated by install.sh

export PYTHONUNBUFFERED=1
export PYTHONPATH="$site_packages_path:\$PYTHONPATH"
exec "$venv_python" "$SCRIPT_DIR/server/main.py"
EOF
    
    chmod +x "$SCRIPT_DIR/run-mcp.sh"
    print_success "Created run-mcp.sh"
}

# Test installation
test_installation() {
    print_header "Testing Installation"
    
    # Test Python syntax
    if $SCRIPT_DIR/.venv/bin/python -m py_compile "$SCRIPT_DIR/server/main.py" 2>/dev/null; then
        print_success "Python syntax check passed"
    else
        print_error "Python syntax check failed"
        return 1
    fi
    
    # Test imports
    if $SCRIPT_DIR/.venv/bin/python -c "from server.tools import mcp; print('OK')" 2>/dev/null; then
        print_success "Module imports working"
    else
        print_error "Module import test failed"
        print_info "Trying with explicit path..."
        cd "$SCRIPT_DIR" && $SCRIPT_DIR/.venv/bin/python -c "import sys; sys.path.insert(0, '.'); from server.tools import mcp; print('OK')" 2>/dev/null && print_success "Module imports working"
    fi
    
    # Test server startup (brief)
    local test_output=$(echo '{"jsonrpc":"2.0","method":"initialize","params":{"protocolVersion":"2025-11-25","capabilities":{},"clientInfo":{"name":"test","version":"0.1.0"}},"id":1}' | timeout 5 "$SCRIPT_DIR/run-mcp.sh" 2>&1 | head -1)
    
    if echo "$test_output" | grep -q "protocolVersion"; then
        print_success "MCP server responds correctly"
    else
        print_error "MCP server test failed"
        print_info "Server output: $test_output"
        return 1
    fi
}

# Configure Claude Desktop
configure_claude() {
    print_header "Claude Desktop Configuration"
    
    local claude_config=""
    
    # Detect OS and set config path
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        claude_config="$HOME/Library/Application Support/Claude/claude_desktop_config.json"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        claude_config="$HOME/.config/Claude/claude_desktop_config.json"
    elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
        # Windows
        claude_config="$APPDATA/Claude/claude_desktop_config.json"
    fi
    
    if [ -z "$claude_config" ]; then
        print_info "Could not detect Claude Desktop config location"
        return 0
    fi
    
    print_info "Claude Desktop config should be at:"
    echo "  $claude_config"
    
    read -p "Would you like to see the configuration snippet? (Y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        echo
        echo "Add this to your claude_desktop_config.json:"
        echo
        cat << EOF
{
  "mcpServers": {
    "lod-mcp": {
      "command": "$SCRIPT_DIR/run-mcp.sh"
    }
  }
}
EOF
        echo
    fi
}

# Main installation
main() {
    print_header "LOD-MCP Installation"
    echo "Luxembourgish Online Dictionary MCP Server"
    echo "Project directory: $SCRIPT_DIR"
    echo
    
    # Pre-flight checks
    print_header "Pre-flight Checks"
    
    if ! detect_python; then
        print_error "Python not found. Please install Python 3.10 or later."
        exit 1
    fi
    
    if ! check_python_version; then
        print_error "Python version too old. Please upgrade to Python 3.10+."
        exit 1
    fi
    
    if ! detect_package_manager; then
        print_error "No package manager found (tried uv, pip3, pip)"
        print_info "Please install uv (recommended): https://github.com/astral-sh/uv"
        print_info "Or ensure pip is available"
        exit 1
    fi
    
    # Installation steps
    create_venv
    install_deps
    create_wrapper
    test_installation
    
    # Success
    print_header "Installation Complete!"
    print_success "LOD-MCP is ready to use"
    echo
    echo "Next steps:"
    echo "  1. Configure Claude Desktop (see below)"
    echo "  2. Restart Claude Desktop completely (Cmd+Q then reopen)"
    echo "  3. Start using the LOD tools in your conversations!"
    echo
    
    configure_claude
    
    print_header "Quick Test"
    echo "Test the installation manually:"
    echo "  $SCRIPT_DIR/run-mcp.sh"
    echo
    print_info "If you see JSON output starting with '{\"jsonrpc\":\"2.0\"...', it's working!"
    echo
}

# Run main function
main "$@"

# Create uninstall script
create_uninstall_script() {
    cat > "$SCRIPT_DIR/uninstall.sh" << 'UNINSTALL_SCRIPT'
#!/bin/bash
#
# LOD-MCP Uninstall Script
# 
# SAFETY: This script does NOT automatically modify Claude Desktop config.
# It only shows you what to remove - you must edit the file manually.
#

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=== LOD-MCP Uninstallation ===${NC}"
echo

# Detect Claude Desktop config
detect_claude_config() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "$HOME/Library/Application Support/Claude/claude_desktop_config.json"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "$HOME/.config/Claude/claude_desktop_config.json"
    elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
        echo "$APPDATA/Claude/claude_desktop_config.json"
    fi
}

CLAUDE_CONFIG=$(detect_claude_config)

# Check if config exists and contains lod-mcp
if [ -n "$CLAUDE_CONFIG" ] && [ -f "$CLAUDE_CONFIG" ]; then
    if grep -q '"lod-mcp"' "$CLAUDE_CONFIG" 2>/dev/null; then
        echo -e "${YELLOW}⚠ IMPORTANT:${NC} You must manually remove lod-mcp from Claude Desktop"
        echo
        echo "Config file location:"
        echo "  $CLAUDE_CONFIG"
        echo
        echo -e "${YELLOW}Step 1:${NC} Edit the config file and remove this section:"
        echo "---"
        grep -A 3 '"lod-mcp"' "$CLAUDE_CONFIG" || true
        echo "---"
        echo
        echo -e "${YELLOW}Step 2:${NC} If 'mcpServers' becomes empty, remove it too:"
        echo '  "mcpServers": {}' 
        echo "  or delete the entire mcpServers section"
        echo
        echo -e "${YELLOW}Step 3:${NC} Save the file and restart Claude Desktop"
        echo
        echo -e "${GREEN}Tip:${NC} Make a backup first:"
        echo "  cp \"$CLAUDE_CONFIG\" \"$CLAUDE_CONFIG.backup.$(date +%Y%m%d)\""
        echo
    fi
fi

# Remove files
echo "Removing LOD-MCP files..."

if [ -d "$SCRIPT_DIR/.venv" ]; then
    read -p "Remove virtual environment (.venv/) ? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$SCRIPT_DIR/.venv"
        echo -e "${GREEN}✓${NC} Removed virtual environment"
    fi
fi

if [ -f "$SCRIPT_DIR/run-mcp.sh" ]; then
    read -p "Remove wrapper script (run-mcp.sh) ? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -f "$SCRIPT_DIR/run-mcp.sh"
        echo -e "${GREEN}✓${NC} Removed wrapper script"
    fi
fi

echo
echo -e "${GREEN}Uninstallation complete!${NC}"
echo
if [ -n "$CLAUDE_CONFIG" ] && [ -f "$CLAUDE_CONFIG" ]; then
    echo -e "${YELLOW}Remember:${NC} If you haven't removed lod-mcp from Claude Desktop config,"
    echo "you'll see errors until you do so and restart Claude."
fi
UNINSTALL_SCRIPT

    chmod +x "$SCRIPT_DIR/uninstall.sh"
    print_success "Created uninstall.sh"
}

# Call the function
create_uninstall_script
